# Generated by Django 4.1.6 on 2023-02-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productImage',
            field=models.ImageField(default='', upload_to='images/products'),
            preserve_default=False,
        ),
    ]
