# Generated by Django 3.2.16 on 2023-02-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_products_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bottleSize',
            field=models.IntegerField(default=250),
            preserve_default=False,
        ),
    ]
