# Generated by Django 3.2.16 on 2023-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_products_bottlesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productDesc',
            field=models.TextField(),
        ),
    ]
