# Generated by Django 3.2.16 on 2023-02-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_products_productdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogName', models.CharField(max_length=255)),
                ('blogImage', models.ImageField(upload_to='images/blogs')),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('productDesc', models.TextField()),
            ],
        ),
    ]
